. "$HOME/.cargo/env"
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH:/usr/local/go/bin:$HOME/.local/bin:$HOME/.bin:$HOME/.dotnet/tools:$HOME/.local/share/gem/ruby/3.0.0/bin"
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_NOLOGO=1
export XDG_CONFIG_HOME=$HOME/.config
export EDITOR=nvim
export VISUAL=nvim
export TERMINAL=ghostty
