#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find -L ~/projects ~/work ~/vaults -mindepth 1 -maxdepth 1 -type d | fzf --prompt "> " --margin=5 --padding=5)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# If we're running outside of tmux.
if [[ -z $TMUX ]]; then
    tmux new-session -A -s $selected_name -c $selected
    exit 0
fi

# If we're inside of tmux and there's existing session attach
if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
